-- VXX__add_admin_permissions.sql

ALTER TABLE admins
    ADD COLUMN can_create BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN can_read BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN can_update BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN can_delete BOOLEAN NOT NULL DEFAULT TRUE;