name: Wise Deployment Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SSH and Run Script
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
           echo "===== DEPLOY ====="
            cd /opt/wiseplayer/backend
            ./deploy.sh
