name: Wise Deployment Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SSH and Run Script
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -xe

            echo "===== SETUP SSH CONFIG ====="
            mkdir -p ~/.ssh
            cat >> ~/.ssh/config << 'EOF'
            Host github.com
              IdentityFile ~/.ssh/github
              StrictHostKeyChecking no
            EOF
            chmod 600 ~/.ssh/config

            echo "===== DEPLOY STARTED ====="
            whoami
            hostname
            pwd

            echo "===== NAVIGATING TO PROJECT ====="
            cd /opt/wiseplayer/backend

            echo "===== GIT INFO ====="
            git branch
            git status

            echo "===== RUNNING DEPLOY SCRIPT ====="
            chmod +x deploy.sh
            ./deploy.sh

            echo "===== DEPLOY FINISHED ====="
